# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d320be01757a42ff26022ad5130038f7bc61745d8e2fc4ba3f4e10f0de0365dddfc8391cbf9cf4816b0a6526d99ffa7a4a2cd2bcd337b2a2fdfcf7a5e0ab8d72

test:
  secret_key_base: 1e88f4d03c5fa96d351f2f63370255e6804604b7551437e775d955461fd76f50a199259baa9111fa626a7239b773f1e0967588e43569205e7b6c4fff3a13ff59

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
